Setup Husky to enforce code quality
humanitech-net/supply-trail pull request #14
Opened 2023-07-25 08:14 UTC by yonas-seyoum

2023-07-25 09:56 UTC, leulsege approved these changes

2023-07-25 16:54 UTC, peterrogov commented
With husky, we need to ensure two key workflows:
- on commit it must run lint-staged
- on push it must run build:release

The second one is very important. Basically the logic is following:
1. `build:release` does a few actions that ensure that project passes linting, builds, and all unit tests work well
2. husky will run this every time a developer tries to push code to repository

By doing this we automatically ensure that at least any piece of code pushed to repository builds, is compliant with lint rules and all unit test have passed. Otherwise you won't be able to push.

Right now in this config husky only does lint-staged.

2023-07-25 16:55 UTC, peterrogov requested changes
Update husky config to comply with my other comment

2023-07-26 05:39 UTC, TeddyAbebe approved these changes
good one

2023-08-04 17:25 UTC, peterrogov approved these changes

2023-08-04 17:55 UTC, merged