frontend boilerplate
humanitech-net/supply-trail pull request #16
Opened 2023-07-25 14:08 UTC by phylipos1234

2023-07-26 05:42 UTC, TeddyAbebe approved these changes
good one

2023-08-09 18:03 UTC, yonas-seyoum approved these changes
Works fine just add eslint and prettier to the boilerplate

2023-08-11 15:28 UTC, peterrogov requested changes
Please fix the directory structure. The app must be in its own separate folder inside `./applications/`. Assuming the folder name for the app is webapp then the full path must be `./applications/webapp/`. Please correct and remove all other unnecessary files.

2023-08-14 07:13 UTC, peterrogov approved these changes

2023-08-14 07:13 UTC, merged