Configure Database Integration
humanitech-net/supply-trail pull request #19
Opened 2023-07-28 14:57 UTC by yonas-seyoum

2023-07-31 16:28 UTC, leulsege approved these changes

2023-07-31 16:37 UTC, leulsege reviewed
first pass all checks

2023-08-11 15:49 UTC, peterrogov requested changes

2023-08-11 15:49 UTC, peterrogov commented on services/service-core/package.json
> +    "rxjs": "^7.8.1",
What is this for?

2023-08-11 15:49 UTC, peterrogov commented on services/service-core/package.json
> +    "rxjs": "^7.8.1",
What is this for?

2023-08-11 15:49 UTC, peterrogov commented on services/service-core/src/app.module.ts
> +        port: +configService.get<number>('DB_PORT'),
Better to use Number(configService.get<number>('DB_PORT')). Use of `+` is technically correct but very obscure and unclear

2023-08-21 13:09 UTC, leulsege reviewed
So, when will you explain to us all of what you do yoni

2023-08-24 11:27 UTC, leulsege approved these changes

2023-08-29 16:56 UTC, peterrogov approved these changes

2023-09-13 16:40 UTC, peterrogov approved these changes

2023-09-14 09:19 UTC, closed without merging